SELECT * FROM INSTRUCTORS
WHERE INSTRUCTORID IN (3,5,7,8);
  
SELECT * FROM INSTRUCTORS
WHERE INSTRUCTORID != 3;

SELECT * FROM INSTRUCTORS
WHERE FIRSTNAME = 'John';

SELECT * FROM INSTRUCTORS
WHERE salary < 4000;

SELECT * FROM INSTRUCTORS
WHERE salary between 60000 and 90000;

SELECT * FROM STUDENTS
WHERE LASTNAME LIKE '%Z';

SELECT * FROM STUDENTS
WHERE LASTNAME LIKE 'J%';

SELECT FIRSTNAME, LASTNAME FROM STUDENTS
WHERE LASTNAME LIKE '%O%';

SELECT * FROM INSTRUCTORS
WHERE SALARY > 50000 AND FIRSTNAME LIKE 'J%' OR FIRSTNAME LIKE 'D%';

SELECT * FROM STUDENTS
WHERE FIRSTNAME IS NOT NULL;

SELECT * FROM STUDENTS
WHERE AGE NOT IN (20);

SELECT COURSEID, COUNT(STUDENTID) 
  FROM STUDENT_COURSE
  GROUP BY COURSEID
  HAVING COUNT(STUDENTID) > 1;

SELECT sum(SALARY) AS 'SALARY TOTAL', avg(salary) AS 'AVG'
FROM INSTRUCTORS;

SELECT MIN(AGE) AS 'MINAGE' , MAX(AGE) AS 'MAXAGE'
FROM STUDENTS;

SELECT ROUND(AGE) AS 'ROUNDAGE'
FROM STUDENTS;
FROM STUDENTS;

SELECT COURSEID, COUNT(*)
FROM STUDENT_COURSES
  GROUP BY COURSEID
  HAVING COUNT(*) > 2;

SELECT AGE, CASE WHEN AGE BETWEEN 18 AND 20 THEN 'TEAM A' ELSE 'TEAM B' END
FROM STUDENTS
  GROUP BY AGE;

-- CONSULTAS SOBRE OTRA BBDD QUE SE HIZO EN EL CURSO
SELECT P.ID, P.NOMBRE, M.ID, M.NOMBRE
FROM PRODUCTOS P
INNER JOIN MARCAS M ON P.MARCA_ID = M.ID
